Fix CentOS image build failure when dib runs on debian based system
Without this fix, building a centos image on Ubuntu for instance will lead to the
following error:
disk-image-create centos7 dhcp-all-interfaces cloud-init-nocloud \
    devuser yum epel baremetal
... dib-run-parts Running tmpdir/hooks/cleanup.d/99-selinux-fixfiles-restore
... Error connecting to audit system.

Change-Id: I229d9b72f88bffddca42da57f01c27e902427071

diff --git a/diskimage_builder/elements/rpm-distro/cleanup.d/99-selinux-fixfiles-restore b/diskimage_builder/elements/rpm-distro/cleanup.d/99-selinux-fixfiles-restore
--- a/diskimage_builder/elements/rpm-distro/cleanup.d/99-selinux-fixfiles-restore
+++ b/diskimage_builder/elements/rpm-distro/cleanup.d/99-selinux-fixfiles-restore
@@ -68,7 +68,8 @@ for MOUNTPOINT in "${SPLIT_MOUNTS[@]}"; do
     if [ "${MOUNTPOINT}" != "/tmp/in_target.d" ] && [ "${MOUNTPOINT}" != "/dev" ] && [ "${MOUNTPOINT}" != "/boot/efi" ]; then
         sudo ${_runcon} chroot ${TARGET_ROOT} \
             /usr/sbin/setfiles -F ${_dash_m} \
-            /etc/selinux/targeted/contexts/files/file_contexts ${MOUNTPOINT}
+            /etc/selinux/targeted/contexts/files/file_contexts ${MOUNTPOINT} \
+            || echo "Warning: Building on $(lsb_release -i | awk '{print $NF}'): SELinux commands might fail"
     fi
 done
 
